// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXjJXGwZgVCbBs2WHtt41xlPLti8eRIRA',
    appId: '1:455006456896:web:0bd32b6518f67aa894e3a5',
    messagingSenderId: '455006456896',
    projectId: 'takesavenue',
    authDomain: 'takesavenue.firebaseapp.com',
    storageBucket: 'takesavenue.firebasestorage.app',
    measurementId: 'G-F7Q5YRG83G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjOQwJtVgoSavKiFrdNBH9tBPE9FbvPCk',
    appId: '1:455006456896:android:a5ff00bcbefb650794e3a5',
    messagingSenderId: '455006456896',
    projectId: 'takesavenue',
    storageBucket: 'takesavenue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqzdOQO0_flRlP0OtwKj5Z4FgpznHRupg',
    appId: '1:455006456896:ios:a5a2f893ffadd9ba94e3a5',
    messagingSenderId: '455006456896',
    projectId: 'takesavenue',
    storageBucket: 'takesavenue.firebasestorage.app',
    iosClientId: '455006456896-5kvqs2a5jsb81chdcn0g047hle27e4u4.apps.googleusercontent.com',
    iosBundleId: 'com.anto.takesavenue',
  );

}